<?php
/**
 * Keyword Research
 *
 * AnswerThePublic-style keyword expansion using Google Suggest autocomplete.
 * Keyless — no API key required.
 *
 * @package MumegaMCP
 * @since   2.8.51
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Keyword research via Google Suggest.
 */
class Spai_Keyword_Research {

	/**
	 * Google Suggest endpoint.
	 *
	 * @var string
	 */
	const SUGGEST_URL = 'https://suggestqueries.google.com/complete/search';

	/**
	 * Maximum HTTP calls per research() invocation.
	 *
	 * Keeps wall-clock time reasonable and avoids hammering the endpoint.
	 *
	 * @var int
	 */
	const MAX_HTTP_CALLS = 25;

	/**
	 * Maximum expansion strings generated by expansions().
	 *
	 * @var int
	 */
	const MAX_EXPANSIONS = 60;

	/**
	 * Question-starter words used by group() to classify questions.
	 *
	 * @var string[]
	 */
	const QUESTION_STARTERS = array(
		'who', 'what', 'when', 'where', 'why', 'how', 'which', 'whose', 'whom',
		'can', 'could', 'does', 'do', 'is', 'are', 'will', 'should', 'would',
	);

	// -------------------------------------------------------------------------
	// Pure methods (unit-testable without HTTP)
	// -------------------------------------------------------------------------

	/**
	 * Build the list of query strings to look up for a given seed.
	 *
	 * Returns the seed itself, the seed with each letter a-z appended (autocomplete
	 * alphabet), and the seed with common question/comparison modifiers prepended or
	 * appended.  Total is capped at MAX_EXPANSIONS and de-duplicated.
	 *
	 * @param string $seed Seed keyword phrase.
	 * @return string[] Unique expansion query strings.
	 */
	public static function expansions( string $seed ): array {
		$seed = trim( $seed );
		$out  = array();

		// Seed itself.
		$out[] = $seed;

		// Alphabet append (a–z).
		foreach ( range( 'a', 'z' ) as $letter ) {
			$out[] = $seed . ' ' . $letter;
		}

		// Question prefix modifiers.
		$question_prefixes = array( 'how', 'what', 'why', 'when', 'where', 'which', 'who' );
		foreach ( $question_prefixes as $prefix ) {
			$out[] = $prefix . ' ' . $seed;
		}

		// Comparison / commercial / local suffix modifiers.
		$suffix_modifiers = array( 'best', 'vs', 'for', 'without', 'near me' );
		foreach ( $suffix_modifiers as $suffix ) {
			$out[] = $seed . ' ' . $suffix;
		}

		// De-duplicate (case-insensitive: keep original case of first occurrence).
		$seen   = array();
		$unique = array();
		foreach ( $out as $item ) {
			$key = strtolower( $item );
			if ( ! isset( $seen[ $key ] ) ) {
				$seen[ $key ] = true;
				$unique[]     = $item;
			}
		}

		// Cap.
		return array_slice( $unique, 0, self::MAX_EXPANSIONS );
	}

	/**
	 * Group a flat list of suggestion strings into questions and keywords.
	 *
	 * Rules:
	 * - Dedup case-insensitively (keep first occurrence's original casing).
	 * - Drop the bare seed string (exact case-insensitive match).
	 * - Classify as a question if the first word is a question-starter word OR
	 *   the phrase contains '?'.
	 * - Everything else goes into keywords.
	 * - Both lists are sorted and returned as re-indexed arrays.
	 *
	 * @param string   $seed        Original seed phrase.
	 * @param string[] $suggestions Flat list of suggestion strings.
	 * @return array{seed: string, keywords: string[], questions: string[], total: int}
	 */
	public static function group( string $seed, array $suggestions ): array {
		$seed_lower = strtolower( trim( $seed ) );

		// Dedup case-insensitively, drop bare seed.
		$seen      = array();
		$deduped   = array();
		foreach ( $suggestions as $item ) {
			$item = trim( (string) $item );
			if ( '' === $item ) {
				continue;
			}
			$key = strtolower( $item );
			if ( $key === $seed_lower ) {
				continue;
			}
			if ( ! isset( $seen[ $key ] ) ) {
				$seen[ $key ] = true;
				$deduped[]    = $item;
			}
		}

		$questions = array();
		$keywords  = array();

		$starters = self::QUESTION_STARTERS;

		foreach ( $deduped as $item ) {
			if ( false !== strpos( $item, '?' ) ) {
				$questions[] = $item;
				continue;
			}
			// Check first word.
			$first_word = strtolower( strtok( $item, " \t\r\n" ) );
			if ( in_array( $first_word, $starters, true ) ) {
				$questions[] = $item;
			} else {
				$keywords[] = $item;
			}
		}

		sort( $questions );
		sort( $keywords );

		return array(
			'seed'      => $seed,
			'keywords'  => array_values( $keywords ),
			'questions' => array_values( $questions ),
			'total'     => count( $keywords ) + count( $questions ),
		);
	}

	// -------------------------------------------------------------------------
	// HTTP method
	// -------------------------------------------------------------------------

	/**
	 * Run keyword research for a seed phrase.
	 *
	 * Fetches Google Suggest for each expansion (up to MAX_HTTP_CALLS), collects
	 * all suggestion strings, then passes them through group() and returns the
	 * result.  Always returns an array on success (never fatals on individual
	 * HTTP failures — those expansions are simply skipped).
	 *
	 * @param string $seed Seed keyword phrase.
	 * @param array  $args {
	 *     Optional arguments.
	 *     @type string $hl  Language code, default 'en'.
	 *     @type string $gl  Country code, default 'us'.
	 *     @type int    $max Overall cap on returned suggestion items, default 100.
	 * }
	 * @return array|WP_Error Result array or WP_Error on invalid input.
	 */
	public static function research( string $seed, array $args = array() ) {
		$seed = trim( $seed );
		if ( '' === $seed ) {
			return new WP_Error( 'empty_seed', __( 'Seed phrase must not be empty.', 'mumega-mcp' ) );
		}

		// Validate locale codes against a BCP-47-ish shape; fall back to defaults on
		// any mismatch rather than silently munging (sanitize_key would garble e.g. zh-TW).
		$locale = static function ( $value, string $default ): string {
			$value = is_string( $value ) ? trim( $value ) : '';
			return preg_match( '/^[a-zA-Z]{2,3}(-[a-zA-Z0-9]{2,8})?$/', $value ) ? $value : $default;
		};
		$hl  = $locale( $args['hl'] ?? '', 'en' );
		$gl  = $locale( $args['gl'] ?? '', 'us' );
		$max = isset( $args['max'] ) ? max( 1, min( 500, absint( $args['max'] ) ) ) : 100;

		$expansions = self::expansions( $seed );
		$to_fetch   = array_slice( $expansions, 0, self::MAX_HTTP_CALLS );

		$collected = array();

		foreach ( $to_fetch as $query ) {
			$url = add_query_arg(
				array(
					'client' => 'firefox',
					'hl'     => $hl,
					'gl'     => $gl,
					'q'      => $query,
				),
				self::SUGGEST_URL
			);

			$response = wp_remote_get(
				$url,
				array( 'timeout' => 5 )
			);

			if ( is_wp_error( $response ) ) {
				// Skip — resilient by design.
				continue;
			}

			$code = wp_remote_retrieve_response_code( $response );
			if ( 200 !== (int) $code ) {
				continue;
			}

			$body = wp_remote_retrieve_body( $response );
			$data = json_decode( $body, true );

			if ( ! is_array( $data ) || ! isset( $data[1] ) || ! is_array( $data[1] ) ) {
				continue;
			}

			foreach ( $data[1] as $suggestion ) {
				if ( is_string( $suggestion ) && '' !== trim( $suggestion ) ) {
					$collected[] = $suggestion;
				}
			}
		}

		// Apply overall cap before grouping.
		$collected = array_slice( $collected, 0, $max );

		$result         = self::group( $seed, $collected );
		$result['note'] = 'Volume and competition data (CPC, search volume, difficulty) require a provider integration such as DataForSEO. This tool returns Google autocomplete signals only.';

		return $result;
	}
}
